#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""P-E: Generate guard-chain map from live engine source (read-only).

Outputs:
  data/_exp_guard_chain_map.json
  references/guard-chain-map.md

This script never changes engine behavior; it only introspects the current
source code and configuration, making the code the single source of truth.
"""
import inspect
import json
import sys
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

import pipeline.item_analysis as ia
import pipeline.trend_health as th
from pipeline import config


ROOT = Path(__file__).resolve().parent.parent
JSON_OUT = ROOT / "data" / "_exp_guard_chain_map.json"
MD_OUT = ROOT / "references" / "guard-chain-map.md"


def src(obj):
    try:
        return inspect.getsource(obj)
    except Exception as exc:  # pragma: no cover - introspection fallback
        return f"<unavailable: {type(exc).__name__}: {exc}>"


def guard_payload():
    out = {}
    for key, fn in ia._GUARDS.items():
        out[key] = {"func": getattr(fn, "__name__", str(fn)), "source": src(fn)}
    return out


def family_payload():
    out = []
    for fam in ia.SIGNAL_FAMILIES:
        out.append({
            "key": fam.key,
            "label": fam.label,
            "priority": fam.priority,
            "limit": fam.limit,
            "guards": list(fam.guards),
            "buckets": list(fam.buckets),
            "sources": list(fam.sources),
            "trigger_source": src(fam.trigger),
        })
    return out


def build_map():
    return {
        "generated_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "engine_version": getattr(config, "ENGINE_VERSION", None),
        "entrypoints": {
            "run_item_analysis_source": src(ia.run_item_analysis),
            "compute_fusion_decision_source": src(th.compute_fusion_decision),
            "decide_fusion_signal_source": src(ia.decide_fusion_signal),
        },
        "guard_sets": {
            "GUARD1": list(ia._GUARD1),
            "GUARD2": list(ia._GUARD2),
            "ALL": list(ia._GUARDS.keys()),
            "POST_FAMILIES": [f.key for f in ia._POST_FAMILIES],
        },
        "guards": guard_payload(),
        "signal_families": family_payload(),
        "liquidity": {
            "score_liquidity_source": src(ia.score_liquidity),
            "liquidity_supply_floor_source": src(th.liquidity_supply_floor),
            "bid_support_source": src(ia.compute_bid_support),
        },
        "helpers": {
            "_apply_guards_source": src(ia._apply_guards),
            "_apply_buy_source": src(ia._apply_buy),
            "_deep_dip_transform_source": src(ia._deep_dip_transform),
        },
        "config": {
            "THRESHOLDS": config.THRESHOLDS,
            "ITEM_EXIT_RULES": config.ITEM_EXIT_RULES,
        },
    }


def markdown(payload):
    lines = []
    lines.append("# Guard Chain Map (generated)")
    lines.append("")
    lines.append(f"Generated: `{payload['generated_at']}`")
    lines.append(f"Engine: `{payload['engine_version']}`")
    lines.append("")
    lines.append("This file is generated by `references/generate_guard_chain_map.py`.")
    lines.append("Do not edit by hand; the code is the source of truth.")
    lines.append("")
    lines.append("## Execution order")
    lines.append("")
    lines.append("1. `run_item_analysis` builds inputs, then calls `compute_fusion_decision`.")
    lines.append("2. `compute_fusion_decision` applies base/oversold/liquidity/event/cycle rules.")
    lines.append("3. `decide_fusion_signal` applies GUARD1, panic upgrade, GUARD2, position, supply-expansion, post families.")
    lines.append("")
    lines.append("### Guard sets")
    lines.append("")
    lines.append(f"- GUARD1: `{', '.join(payload['guard_sets']['GUARD1'])}`")
    lines.append(f"- GUARD2: `{', '.join(payload['guard_sets']['GUARD2'])}`")
    lines.append(f"- POST_FAMILIES: `{', '.join(payload['guard_sets']['POST_FAMILIES'])}`")
    lines.append("")
    lines.append("## Guard sources")
    lines.append("")
    for key in payload["guard_sets"]["ALL"]:
        guard = payload["guards"][key]
        lines.append(f"### {key} (`{guard['func']}`)")
        lines.append("")
        lines.append("```python")
        lines.append(guard["source"].rstrip())
        lines.append("```")
        lines.append("")
    lines.append("## Signal families")
    lines.append("")
    for fam in payload["signal_families"]:
        lines.append(f"### {fam['key']}")
        lines.append("")
        lines.append(f"- label: `{fam['label']}`")
        lines.append(f"- priority: `{fam['priority']}`")
        lines.append(f"- limit: `{fam['limit']}`")
        lines.append(f"- guards: `{', '.join(fam['guards'])}`")
        lines.append(f"- buckets: `{', '.join(fam['buckets'])}`")
        lines.append(f"- sources: `{', '.join(fam['sources'])}`")
        lines.append("")
        lines.append("```python")
        lines.append(fam["trigger_source"].rstrip())
        lines.append("```")
        lines.append("")
    lines.append("## Liquidity")
    lines.append("")
    lines.append("### score_liquidity")
    lines.append("")
    lines.append("```python")
    lines.append(payload["liquidity"]["score_liquidity_source"].rstrip())
    lines.append("```")
    lines.append("")
    lines.append("### liquidity_supply_floor")
    lines.append("")
    lines.append("```python")
    lines.append(payload["liquidity"]["liquidity_supply_floor_source"].rstrip())
    lines.append("```")
    lines.append("")
    lines.append("### compute_bid_support")
    lines.append("")
    lines.append("```python")
    lines.append(payload["liquidity"]["bid_support_source"].rstrip())
    lines.append("```")
    lines.append("")
    lines.append("## Config")
    lines.append("")
    lines.append("```json")
    lines.append(json.dumps(payload["config"], ensure_ascii=False, indent=2))
    lines.append("```")
    lines.append("")
    return "\n".join(lines)


def main():
    payload = build_map()
    JSON_OUT.parent.mkdir(parents=True, exist_ok=True)
    JSON_OUT.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    MD_OUT.write_text(markdown(payload), encoding="utf-8")
    print(f"wrote {JSON_OUT}")
    print(f"wrote {MD_OUT}")
    print(f"guards={len(payload['guards'])} families={len(payload['signal_families'])}")


if __name__ == "__main__":
    main()
