# -*- coding: utf-8 -*-
"""A1-2 probe: deep_value sentiment 65->75 no-man-zone replay.

Read-only research probe. Does NOT change production thresholds.
It reuses the archived single-item replay runner and monkeypatches only the
deep_value trigger inside pipeline.item_analysis, so both control and variant
are generated by the same current engine code.

Output: data/_exp_a1_2_sent_gap.json
"""
import json
from collections import Counter
from datetime import datetime
from importlib.util import spec_from_file_location, module_from_spec
from pathlib import Path

import sys
sys.path.insert(0, ".")

BASE = Path(__file__).resolve().parent.parent
START, END, WARMUP = "2025-08-13", "2026-08-05", 30
OUT = BASE / "data" / "_exp_a1_2_sent_gap.json"

# The exact 2025-08-10 start is no longer reproducible because 365d retention has
# advanced. Reuse the standard replay's 96-item pool and run control/variant on
# the currently retained window so the A/B is apples-to-apples.
_STD = json.load(open(BASE / "data" / "item_backtest_full_2025.json", encoding="utf-8"))
_POOL_NAMES = [r["name"] for r in _STD["per_item"]]

_ARCHIVED_RUNNER = BASE / "references" / "scripts-archive" / "run_item_backtest.py"
spec = spec_from_file_location("rib", str(_ARCHIVED_RUNNER))
rib = module_from_spec(spec)
spec.loader.exec_module(rib)

from pipeline.backtest_common import build_market_context
from pipeline.backtest_methodology import (
    signal_cluster_report,
    walk_forward_split,
    permutation_baseline,
)
from pipeline import db


def pool_a_items():
    """Standard replay pool by name, mapped to current item ids."""
    conn = db.get_conn()
    qmarks = ",".join("?" * len(_POOL_NAMES))
    rows = conn.execute(
        f"SELECT id, name FROM items WHERE name IN ({qmarks})",
        _POOL_NAMES,
    ).fetchall()
    pool = {r["id"]: r["name"] for r in rows if r["name"] not in rib.EXCLUDED_ITEMS}
    # Fall back to signal names when a per-item name changed.
    missing = [n for n in _POOL_NAMES if n not in {r["name"] for r in rows}]
    if missing:
        sig_names = sorted({s["name"] for s in _STD["signals"]})
        qmarks2 = ",".join("?" * len(sig_names))
        rows2 = conn.execute(
            f"SELECT id, name FROM items WHERE name IN ({qmarks2})",
            sig_names,
        ).fetchall()
        for r in rows2:
            if r["name"] not in rib.EXCLUDED_ITEMS:
                pool[r["id"]] = r["name"]
    conn.close()
    return pool


def _deep_value_sent75(F):
    return (
        F["pct"] is not None and F["pct"] <= 20
        and F["z"] is not None and F["z"] <= -0.5
        and F["th"] >= 35 and F["market_th"] >= 40
        and (F["mchg30"] is None or F["mchg30"] <= -3)
        and 40 <= F["sent"] <= 75 and F["drop21"] >= -5
        and not rib.ia._dedup_hit(F["recent_buy_dates"], F["signal_date"])
    )


_ORIGINAL_TRIGGER = rib.ia.SIGNAL_FAMILY_BY_KEY["deep_value"].trigger


def set_deep_value_sent75(enabled):
    fam = rib.ia.SIGNAL_FAMILY_BY_KEY["deep_value"]
    fam.trigger = _deep_value_sent75 if enabled else _ORIGINAL_TRIGGER


def run_backtest(patched):
    set_deep_value_sent75(patched)
    rib.patch_sentiment(50.0)
    market_ctx = build_market_context(START, end=END)
    items = pool_a_items()
    signals = []
    t0 = datetime.now()
    for n_i, (iid, iname) in enumerate(sorted(items.items()), 1):
        r = rib.backtest_item(iid, iname, START, END, WARMUP, market_ctx, cost=0.02)
        signals.extend(s for s in r.get("signals", []) if s.get("fwd14") is not None)
        if n_i % 20 == 0:
            print(f"  [{n_i}/{len(items)}] sig={len(signals)} elapsed={str(datetime.now()-t0)[:8]}", flush=True)
    return signals


def stats(sigs):
    n = len(sigs)
    rets = [s.get("net14") for s in sigs if s.get("net14") is not None]
    if not rets:
        return {"n": n, "n14": 0, "win14_pct": None, "avg14": None}
    wins = sum(1 for x in rets if x > 0)
    return {
        "n": n,
        "n14": len(rets),
        "win14_pct": round(100.0 * wins / len(rets), 1),
        "avg14": round(sum(rets) / len(rets), 2),
    }


def main():
    print("control replay", flush=True)
    control = run_backtest(False)
    print("variant replay (deep_value sent<=75)", flush=True)
    variant = run_backtest(True)

    ctrl_keys = {(s["name"], s["date"]) for s in control}
    var_keys = {(s["name"], s["date"]) for s in variant}
    added = [s for s in variant if (s["name"], s["date"]) not in ctrl_keys]
    removed = [s for s in control if (s["name"], s["date"]) not in var_keys]
    changed = [
        (a, b) for a in control for b in variant
        if (a["name"], a["date"]) == (b["name"], b["date"]) and a.get("signal_type") != b.get("signal_type")
    ]

    added_net = [s["net14"] for s in added if s.get("net14") is not None]
    added_sent = Counter()
    for s in added:
        sent = s.get("sentiment")
        if sent is None:
            added_sent["None"] += 1
        elif 40 <= sent <= 65:
            added_sent["40-65"] += 1
        elif 65 < sent <= 75:
            added_sent["66-75"] += 1
        else:
            added_sent["other"] += 1

    added_cluster = signal_cluster_report([s["date"] for s in added], window=3)
    added_wf = walk_forward_split(added, anchor_ratio=0.7, return_field="net14", min_samples=5)
    added_perm = permutation_baseline(added_net, n_perm=500, seed=42)

    half = sorted(added, key=lambda s: s["date"])
    mid = len(half) // 2
    first, second = half[:mid], half[mid:]

    out = {
        "meta": "A1-2 probe: deep_value sentiment upper bound 65->75; read-only; production unchanged",
        "generated": datetime.now().strftime("%Y-%m-%d %H:%M"),
        "window": {"start": START, "end": END, "warmup": WARMUP, "pool": "A(98 legacy items)"},
        "control": stats(control),
        "variant": stats(variant),
        "set_diff": {
            "added_signals": len(added),
            "removed_signals": len(removed),
            "family_changed_same_day": len(changed),
        },
        "added": stats(added),
        "added_sentiment_buckets": dict(added_sent),
        "added_cluster": added_cluster,
        "added_walk_forward": added_wf,
        "added_permutation": added_perm,
        "added_half_split": {
            "first": stats(first),
            "second": stats(second),
            "split_index": mid,
        },
        "added_sample": sorted(
            [
                {
                    "name": s["name"],
                    "date": s["date"],
                    "sentiment": s.get("sentiment"),
                    "signal_type": s.get("signal_type"),
                    "pct": s.get("pct"),
                    "z": s.get("z"),
                    "mkt_chg30": s.get("mkt_chg30"),
                    "fwd14": s.get("fwd14"),
                    "net14": s.get("net14"),
                }
                for s in added
            ],
            key=lambda x: (x["date"], x["name"]),
        ),
    }

    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(out, f, ensure_ascii=False, indent=2)

    print("\n=== summary ===", flush=True)
    print("control", stats(control), flush=True)
    print("variant", stats(variant), flush=True)
    print("added", stats(added), "sent", dict(added_sent), flush=True)
    print("removed", len(removed), "family_changed_same_day", len(changed), flush=True)
    print("added_cluster", {k: added_cluster[k] for k in ("signal_count", "event_count", "max_cluster_share", "flagged")}, flush=True)
    print("added_wf", {k: added_wf[k] for k in ("train", "test", "valid", "reason")}, flush=True)
    print("added_perm", {k: added_perm[k] for k in ("n", "observed_win_rate", "observed_avg", "perm_mean_win_rate", "p_value")}, flush=True)
    print("written:", OUT, flush=True)


if __name__ == "__main__":
    main()

