# -*- coding: utf-8 -*-
"""期望统计双基线同步器（J-3 口径，2026-08-07 定稿，2026-08-14 改双基线）。

HIST-FULL = data/item_backtest_full_2025.json（v2-T4/T5 冻结归档）；CLEAN-CUR = data/_exp_v2t8_win_replay.json（v2-T8 展示参考）。
本脚本把回放产物按展示键（panic / deep_value / accumulate）重算
n / events / win14 / avg14 / ci14 / win30 / avg30，并同步写入：

  1) pipeline/config.py 的 ITEM_EXPECTANCY_STATS（防止手工双写漂移，该块勿手改）
  2) data/signal_event_counts.json（调用 j1_event_counts.py 同口径重算，供进度卡 J-3 展示）

用法: python references/sync_expectancy_config.py
改回放产物（重跑 run_item_backtest_full.py / 调整引擎）后必须重跑本脚本；
tests/test_smoke.py 的 t_expectancy_sync 硬校验 config 与回放计算值一致（防漂移）。
"""
import io
import json
import os
import re
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import j1_event_counts as j1  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
CONFIG = ROOT / "pipeline" / "config.py"
REPLAY = ROOT / "data" / "item_backtest_full_2025.json"
REPLAY_CLEAN = ROOT / "data" / "_exp_v2t8_win_replay.json"

sys.path.insert(0, str(ROOT))
from pipeline.config import SIGNAL_FAMILY_TAXONOMY  # noqa: E402

DISPLAY_KEYS = tuple(SIGNAL_FAMILY_TAXONOMY["display_keys"])
LABELS = SIGNAL_FAMILY_TAXONOMY["display_labels"]
FINE_TO_DISPLAY = SIGNAL_FAMILY_TAXONOMY["fine_to_display"]
FINE_LABELS = SIGNAL_FAMILY_TAXONOMY["fine_labels"]


def compute_display_stats(replay_path=None):
    """按展示键重算期望统计（与 j1_event_counts.display_keys 完全同口径）。

    返回 (stats, total_signals, composition)：
      stats[key] = {n, events, win14, avg14, ci14_lo, ci14_hi, win30, avg30, n30}
      composition[key] = [("恐慌共振", 46), ...]（生成构成注释用）
    """
    path = Path(replay_path) if replay_path else REPLAY
    data = json.load(io.open(path, encoding="utf-8"))
    signals = data["signals"]
    stats, composition = {}, {}
    for key in DISPLAY_KEYS:
        sigs = [s for s in signals if j1.display_key(s.get("action_label") or "") == key]
        st = j1.family_stats([s["date"] for s in sigs])
        p14 = j1.pnl_stats(sigs)
        ci = p14["win14"]["ci"] or (None, None)
        stats[key] = {
            "n": len(sigs),
            "events": st["events"],
            "win14": p14["win14"]["win"],
            "avg14": p14["win14"]["avg"],
            "ci14_lo": ci[0],
            "ci14_hi": ci[1],
            "win30": p14["win30"]["win"],
            "avg30": p14["win30"]["avg"],
            "n30": p14["win30"]["n"],
        }
        comp = {}
        for s in sigs:
            fine = j1.assign_family(s.get("action_label") or "")
            comp[fine] = comp.get(fine, 0) + 1
        composition[key] = [(FINE_LABELS[f], n) for f, n in sorted(comp.items(), key=lambda kv: -kv[1])]
    return stats, len(signals), composition


def render_block(stats, total, composition, var_name="ITEM_EXPECTANCY_STATS",
                 replay_path=None, baseline_label="HIST-FULL", caveat=""):
    lines = []
    lines.append("%s = {" % var_name)
    lines.append("    # auto-generated by references/sync_expectancy_config.py; do not hand-edit.")
    lines.append("    # baseline: %s | replay: %s | signals: %d | net 2%%" % (
        baseline_label, replay_path, total))
    if caveat:
        lines.append("    # caveat: %s" % caveat)
    lines.append("    # display keys match action_label (panic/deep_value/accumulate); events = +/-3d clusters.")
    lines.append("    # win30/avg30 are n30 subsets; ci14 = Wilson 95% interval.")
    for key in DISPLAY_KEYS:
        v = stats[key]
        comp_txt = " + ".join("%s(%d)" % (lab, n) for lab, n in composition[key])
        lines.append('    # %s：%s 全量（自动生成）' % (LABELS[key], comp_txt))
        lines.append('    "%s": {' % key)
        lines.append('        "label": "%s",' % LABELS[key])
        lines.append('        "n": %d,' % v["n"])
        lines.append('        "events": %d,' % v["events"])
        lines.append('        "win14": %.1f, "avg14": %.2f, "ci14_lo": %.1f, "ci14_hi": %.1f,' % (
            v["win14"], v["avg14"], v["ci14_lo"], v["ci14_hi"]))
        lines.append('        "win30": %.1f, "avg30": %.2f,  # n30=%d' % (v["win30"], v["avg30"], v["n30"]))
        lines.append('    },')
    lines.append("}")
    return "\n".join(lines)


def _replace_block(src, var_name, block):
    pat = re.compile(re.escape(var_name) + r" = \{(?s:.*?)\n\}")
    new_src, n_sub = pat.subn(lambda _m: block, src, count=1)
    if n_sub != 1:
        raise RuntimeError("config.py 未找到 %s 块，中止同步" % var_name)
    return new_src


def sync():
    hist_stats, hist_total, hist_comp = compute_display_stats(REPLAY)
    clean_stats, clean_total, clean_comp = compute_display_stats(REPLAY_CLEAN)
    clean_panic_share = round(100.0 * clean_stats["panic"]["n"] / clean_total, 1) if clean_total else 0.0
    clean_caveat = ("CLEAN-CUR: %d signals, v2-T8, panic single-event share %.1f%%, "
                    "missing 2026-02~04 bull segment") % (clean_total, clean_panic_share)

    hist_block = render_block(hist_stats, hist_total, hist_comp,
                              var_name="ITEM_EXPECTANCY_STATS", replay_path=str(REPLAY),
                              baseline_label="HIST-FULL",
                              caveat="HIST-FULL: 317 signals, v2-T4/T5, contains ~50% missing-depth signals")
    clean_block = render_block(clean_stats, clean_total, clean_comp,
                               var_name="ITEM_EXPECTANCY_STATS_CLEAN_CUR", replay_path=str(REPLAY_CLEAN),
                               baseline_label="CLEAN-CUR",
                               caveat=clean_caveat)

    src = io.open(CONFIG, encoding="utf-8").read()
    # normalize an empty clean block so the regex below can replace it
    src = src.replace("ITEM_EXPECTANCY_STATS_CLEAN_CUR = {}", "ITEM_EXPECTANCY_STATS_CLEAN_CUR = {\n}")
    new_src = _replace_block(src, "ITEM_EXPECTANCY_STATS", hist_block)
    new_src = _replace_block(new_src, "ITEM_EXPECTANCY_STATS_CLEAN_CUR", clean_block)
    if new_src != src:
        io.open(CONFIG, "w", encoding="utf-8", newline="").write(new_src)
        print("updated pipeline/config.py ITEM_EXPECTANCY_STATS / ITEM_EXPECTANCY_STATS_CLEAN_CUR")
    else:
        print("pipeline/config.py 双基线期望统计无变化")

    # J-3 progress card: keep HIST-FULL at top level for backward compatibility,
    # and add both labelled baselines under `baselines` (no bare numbers).
    hist_payload = j1.generate_payload(str(REPLAY), source_label="HIST-FULL")
    clean_payload = j1.generate_payload(str(REPLAY_CLEAN), source_label="CLEAN-CUR")
    clean_payload["note"] = "CLEAN-CUR baseline (" + str(REPLAY_CLEAN) + "): same display-key mapping as HIST-FULL"
    out = {k: v for k, v in hist_payload.items()}
    out["baselines"] = {"HIST-FULL": hist_payload, "CLEAN-CUR": clean_payload}
    with io.open(ROOT / "data" / "signal_event_counts.json", "w", encoding="utf-8", newline="\n") as f:
        json.dump(out, f, ensure_ascii=False, indent=1)
    print("updated data/signal_event_counts.json")

    return hist_stats, hist_total, hist_comp


if __name__ == "__main__":
    stats, total, composition = sync()
    print("=== HIST-FULL 期望统计（%d 信号）===" % total)
    for key in DISPLAY_KEYS:
        v = stats[key]
        print("%-12s n=%3d n30=%3d events=%2d win14=%5.1f avg14=%6.2f ci14=[%4.1f,%4.1f] win30=%5.1f avg30=%6.2f" % (
            key, v["n"], v["n30"], v["events"], v["win14"], v["avg14"],
            v["ci14_lo"], v["ci14_hi"], v["win30"], v["avg30"]))
