body = []

body.append("")
body.append("## Workflow C: Trade Recommendation")
body.append("")
body.append("### C1. Gather Item Data")
body.append("")
body.append("Fetch price history for the specific item:")
body.append("")
body.append('```bash')
body.append('python scripts/fetch_prices.py "ITEM" --days 60 --output item.json')
body.append('python scripts/analyze.py item.json --output report.md')
body.append('```')
body.append("")
body.append("### C2. Score the Item")
body.append("")
body.append("Apply valuation model from `references/skin-valuation.md`.")
body.append("")
body.append("### C3. Check Events")
body.append("")
body.append("Cross-reference with `references/market-analysis.md` event calendar.")
body.append("")
body.append("### C4. Apply Strategy Rules")
body.append("")
body.append("Consult `references/trading-strategies.md`:")
body.append("- Which buy/sell strategy applies")
body.append("- Stop-loss and take-profit levels")
body.append("- Position sizing recommendation")
body.append("")
body.append("### C5. Output Recommendation")
body.append("")
body.append("Structured format:")
body.append("- **Rating**: S/A/B/C/D")
body.append("- **Action**: Buy / Hold / Sell / Wait")
body.append("- **Entry Price**: Suggested buy range")
body.append("- **Stop Loss**: Price level")
body.append("- **Take Profit**: Price targets")
body.append("- **Time Horizon**: Expected hold period")
body.append("- **Thesis**: 2-3 sentence rationale")
body.append("- **Risks**: Key downside risks")

path = r"C:\Users\81572\Desktop\codex\cs-model\cs-skin-market\SKILL.md"
with open(path, "a", encoding="utf-8") as f:
    f.write("\n".join(body))

print("Part 3 appended")
