import json

body = []

body.append("# CS Skin Market Strategy")
body.append("")
body.append("## Overview")
body.append("")
body.append("Assists with CS (Counter-Strike) skin market investment: market trend analysis, skin valuation and filtering, buy/sell timing, and portfolio management. Load references/ for domain knowledge when needed.")
body.append("")
body.append("## Quick Start")
body.append("")
body.append("When a user asks about CS skins, follow this decision tree:")
body.append("")
body.append("1. **Market overview request** -> Workflow A: Market Analysis")
body.append("2. **Find/select skins to invest** -> Workflow B: Skin Selection")
body.append("3. **Should I buy/sell X?** -> Workflow C: Trade Recommendation")
body.append("4. **Portfolio review** -> Workflow D: Portfolio Report")
body.append("")
body.append("If user request is ambiguous, ask one clarifying question, then proceed.")
body.append("")
body.append("---")
body.append("")
body.append("## Workflow A: Market Analysis")
body.append("")
body.append("### A1. Gather Market Context")
body.append("")
body.append("Use `web_search` to find recent CS market news:")
body.append("- Upcoming or recent Steam sales")
body.append("- Major tournament schedules")
body.append("- New case or operation releases")
body.append("- CS2 update news")
body.append("")
body.append("### A2. Fetch Price Data")
body.append("")
body.append("Run `scripts/fetch_prices.py` for the items of interest:")
body.append("")
body.append('```bash')
body.append('python scripts/fetch_prices.py "ITEM_NAME" --days 30 --output data.json')
body.append('```')
body.append("")
body.append("For general market temperature, check 3-5 representative items across different tiers:")
body.append("- High-tier: e.g. AK-47 | Fire Serpent, AWP | Dragon Lore")
body.append("- Mid-tier: e.g. AK-47 | Redline, M4A4 | Asiimov")
body.append("- Entry-tier: e.g. AK-47 | Elite Build, AWP | Worm God")
body.append("")
body.append("### A3. Analyze")
body.append("")
body.append("Run `scripts/analyze.py` on each data file:")
body.append("")
body.append('```bash')
body.append('python scripts/analyze.py data.json')
body.append('```')
body.append("")
body.append("### A4. Interpret")
body.append("")
body.append("Cross-reference results with `references/market-analysis.md`:")
body.append("- Identify market cycle phase")
body.append("- Check event-driven factors")
body.append("- Assess market sentiment indicators")
body.append("")
body.append("### A5. Present")
body.append("")
body.append("Output a structured summary:")
body.append("- Current market phase and overall sentiment")
body.append("- 3-5 key observations with supporting data")
body.append("- Risk factors to watch")

# Write part 1
path = r"C:\Users\81572\Desktop\codex\cs-model\cs-skin-market\SKILL.md"
with open(path, "r", encoding="utf-8") as f:
    content = f.read()

parts = content.split("---", 2)
frontmatter = parts[1]

with open(path, "w", encoding="utf-8") as f:
    f.write("---" + frontmatter + "---\n" + "\n".join(body))

print("Part 1 written")
