body = []

body.append("")
body.append("## Workflow D: Portfolio Report")
body.append("")
body.append("### D1. List Holdings")
body.append("")
body.append("Ask user for current holdings (items + purchase prices + dates).")
body.append("")
body.append("### D2. Assess Each")
body.append("")
body.append("Fetch and analyze current prices for each holding.")
body.append("")
body.append("### D3. Portfolio Health")
body.append("")
body.append("Calculate:")
body.append("- Total portfolio value and PnL")
body.append("- Concentration risk (single item / category)")
body.append("- Average rating distribution")
body.append("- Liquidity coverage")
body.append("")
body.append("### D4. Rebalancing Suggestions")
body.append("")
body.append("Based on `references/trading-strategies.md`:")
body.append("- Which holdings to trim (overvalued, above take-profit)")
body.append("- Which holdings to add (undervalued, dips)")
body.append("- Cash reserve recommendation")
body.append("")
body.append("---")
body.append("")
body.append("## Resources")
body.append("")
body.append("### references/")
body.append("")
body.append("Load relevant references based on user request:")
body.append("- `market-analysis.md` -- methodology for market trend analysis")
body.append("- `skin-valuation.md` -- 5-factor valuation model")
body.append("- `trading-strategies.md` -- buy/sell strategies and risk management")
body.append("")
body.append("### scripts/")
body.append("")
body.append("- `fetch_prices.py` -- Fetch Steam Market price history")
body.append("- `analyze.py` -- Run technical analysis (MA, MACD, volatility)")
body.append("")
body.append("### assets/")
body.append("")
body.append("Store generated reports and data files here.")
body.append("")
body.append("---")
body.append("")
body.append("## Important Notes")
body.append("")
body.append("1. **Data limitations**: Steam Market API provides USD prices and limited history. For RMB pricing and richer data, mention that Buff163/UUYP require web scraping.")
body.append("2. **Not financial advice**: Always include a disclaimer that this is informational analysis, not financial advice.")
body.append("3. **Market is volatile**: CS skin markets can be highly volatile. Highlight risk factors prominently.")
body.append("4. **When data is unavailable**: If API fails or returns empty, use `web_search` to find recent price discussions on forums/Reddit as a fallback.")

path = r"C:\Users\81572\Desktop\codex\cs-model\cs-skin-market\SKILL.md"
with open(path, "a", encoding="utf-8") as f:
    f.write("\n".join(body))

print("Part 4 appended - SKILL.md complete")
