body = []

body.append("")
body.append("## Workflow B: Skin Selection")
body.append("")
body.append("### B1. Understand Requirements")
body.append("")
body.append("Clarify with user if not stated:")
body.append("- Budget range")
body.append("- Time horizon (short-term flip / medium hold / long-term)")
body.append("- Risk tolerance (conservative / moderate / aggressive)")
body.append("- Weapon type preference (any or specific)")
body.append("")
body.append("### B2. Screen Candidates")
body.append("")
body.append("Apply filters from `references/skin-valuation.md`:")
body.append("- Minimum liquidity threshold (>= 10 daily trades)")
body.append("- Rarity tier filter based on budget")
body.append("- Weapon type heat map")
body.append("")
body.append("### B3. Score Candidates")
body.append("")
body.append("Use the 5-factor scoring model in `references/skin-valuation.md`:")
body.append("1. Rarity (30%)")
body.append("2. Wear/Float (25%)")
body.append("3. Sticker Value (20%)")
body.append("4. Liquidity (15%)")
body.append("5. Weapon Popularity (10%)")
body.append("")
body.append("### B4. Present Recommendations")
body.append("")
body.append("Output a ranked list:")
body.append("")
body.append("```")
body.append("| Rank | Item | Score | Price | Liquidity | Thesis |")
body.append("|---|---|---|---|---|---|")
body.append("| 1 | ... | 4.2 (S) | $XX | High | ... |")
body.append("| 2 | ... | 3.5 (A) | $XX | Medium | ... |")
body.append("```")
body.append("")
body.append("Include watch-list items (B-grade with upward catalysts) and avoid-list items (D-grade / red flags).")

# Append to SKILL.md
path = r"C:\Users\81572\Desktop\codex\cs-model\cs-skin-market\SKILL.md"
with open(path, "a", encoding="utf-8") as f:
    f.write("\n".join(body))

print("Part 2 appended")
